version: '3'
services:
  db:
    container_name: mysqldb
    image: mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: calendrierDB
    volumes:
      - ./mysql:/var/lib/mysql

  backend:
    build: ./spring-boot
    restart: always
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/calendrierDB?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

  frontend:
    build: ./angular
    ports:
      - "4200:80"
    depends_on:
      - backend
